# Generated by Django 3.0.12 on 2021-03-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210227_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='name',
            field=models.CharField(choices=[('FreeTrial', 'Free Trial'), ('Basic', 'Basic'), ('Essential', 'Essential'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual'), ('Team', 'Team'), ('Organisation', 'Organisation')], default='FreeTrial', max_length=100, verbose_name='Pricing Type'),
        ),
    ]
