# Generated by Django 3.0.12 on 2021-03-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20210309_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
