# Generated by Django 3.0.12 on 2021-03-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20210310_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='freeTrialEndDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Next Payment Due'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='nextPaymentDueDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Next Payment Due'),
        ),
    ]
