# Generated by Django 3.0.12 on 2021-03-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20210320_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='freeTrialEndDate',
            field=models.DateTimeField(verbose_name='Free Trial End Date'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='nextPaymentDueDate',
            field=models.DateTimeField(verbose_name='Next Payment Due'),
        ),
    ]
