# Generated by Django 3.0.12 on 2021-03-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20210321_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='description',
            field=models.TextField(blank=True, max_length=4000, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='is_default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
