# Generated by Django 3.0.12 on 2021-04-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20210405_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='nextPaymentDueDate',
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='period_end',
            field=models.DateTimeField(null=True, verbose_name='Period End Date'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='period_start',
            field=models.DateTimeField(null=True, verbose_name='Period Start Date'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stripe payment Method Id'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subscription Status'),
        ),
    ]
