# Generated by Django 3.2 on 2021-04-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_auto_20210406_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='cardId',
            field=models.CharField(blank=True, max_length=60, verbose_name='card Id'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=60, verbose_name='Unique card finger print'),
        ),
    ]
