# Generated by Django 3.2 on 2021-04-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20210410_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.CharField(blank=True, choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, verbose_name='Card Expiry Month'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031')], max_length=4, verbose_name='Card Expiry Year'),
        ),
    ]
