# Generated by Django 3.1.12 on 2021-07-01 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quote.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vatRate', '0003_auto_20210701_2200'),
        ('leads', '0020_auto_20210621_2122'),
        ('country', '0005_auto_20210628_2211'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0003_auto_20210628_2211'),
        ('organisation', '0010_organisation_industry'),
        ('product', '0004_auto_20210701_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('quote_id', models.CharField(default='EST-', max_length=100, verbose_name='Quote ID')),
                ('reference', models.CharField(max_length=200, verbose_name='Reference')),
                ('deal_name', models.CharField(max_length=200, verbose_name='Deal Name')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('start_date', models.DateField(auto_now=True, verbose_name=' Valid from')),
                ('end_date', models.DateField(auto_now=True, verbose_name=' Valid to')),
                ('contactType', models.CharField(choices=[('Lead', 'lead'), ('Contact', 'contact'), ('Account', 'account')], default=None, max_length=25, verbose_name='Contact Type')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.'), ('Ms.', 'Ms.'), ('', 'Prefer not to say')], default='', max_length=25, verbose_name='Title')),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('work_org_name', models.CharField(blank=True, max_length=200, verbose_name='Work organisation')),
                ('billing_address1', models.CharField(blank=True, max_length=200, verbose_name='Address Line 1')),
                ('billing_address2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('billing_address3', models.CharField(blank=True, max_length=200, verbose_name='Address Line 3')),
                ('billing_address4', models.CharField(blank=True, max_length=200, verbose_name='Address Line 4')),
                ('billing_address_city', models.CharField(blank=True, max_length=60, verbose_name='City')),
                ('billing_address_state_county', models.CharField(blank=True, max_length=60, verbose_name='State/County')),
                ('billing_address_postcode', models.CharField(blank=True, max_length=60, verbose_name='State/County')),
                ('shipping_address1', models.CharField(blank=True, max_length=200, verbose_name='Address Line 1')),
                ('shipping_address2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('shipping_address3', models.CharField(blank=True, max_length=200, verbose_name='Address Line 3')),
                ('shipping_address4', models.CharField(blank=True, max_length=200, verbose_name='Address Line 4')),
                ('shipping_address_city', models.CharField(blank=True, max_length=60, verbose_name='City')),
                ('shipping_address_state_county', models.CharField(blank=True, max_length=60, verbose_name='State/County')),
                ('shipping_address_postcode', models.CharField(blank=True, max_length=60, verbose_name='State/County')),
                ('terms_conditions', models.TextField(blank=True, max_length=400)),
                ('notes', models.TextField(blank=True, max_length=400)),
                ('sub_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Sub Total')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Discount')),
                ('shipping_charges', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Shipping Charges')),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Shipping Charges')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Total')),
                ('file', models.FileField(blank=True, null=True, upload_to=quote.models.quote_attachment_directory_path)),
                ('dateTimeModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('billing_address_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_country', to='country.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_added_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.currency')),
                ('leadId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_modified_by', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_owned_by', to=settings.AUTH_USER_MODEL)),
                ('shipping_address_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_country', to='country.country')),
                ('shipping_vat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vatRate.vatrate')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('dateTimeModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
            ],
            options={
                'verbose_name': 'Quote Stage',
                'verbose_name_plural': 'Quote Stages',
            },
        ),
        migrations.CreateModel(
            name='QuotedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='Quantity')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Cost of items')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Discount on item')),
                ('dateTimeModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoteItem_added_by', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoteItem_modified_by', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted_items', to='quote.quote')),
                ('vat_rate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vatRate.vatrate')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quote.stage'),
        ),
    ]
