# Generated by Django 3.1.12 on 2021-07-01 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vatRate', '0003_auto_20210701_2200'),
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shipping_vat',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vatRate.vatrate'),
        ),
    ]
