# Generated by Django 3.1.12 on 2021-07-04 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20210701_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteditem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=' Valid to'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=' Valid from'),
        ),
        migrations.AlterField(
            model_name='quoteditem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
