# Generated by Django 3.1.12 on 2021-07-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20210704_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='billing_address1',
            field=models.CharField(max_length=200, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='billing_address_city',
            field=models.CharField(max_length=60, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='billing_address_postcode',
            field=models.CharField(max_length=60, verbose_name='State/County'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='work_org_name',
            field=models.CharField(max_length=200, verbose_name='Work organisation'),
        ),
        migrations.AlterField(
            model_name='quoteditem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Discount'),
        ),
    ]
