# Generated by Django 3.1.12 on 2021-07-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20210704_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Discount %'),
        ),
        migrations.AlterField(
            model_name='quoteditem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Discount %'),
        ),
        migrations.AlterField(
            model_name='quoteditem',
            name='line_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Total'),
        ),
    ]
