# Generated by Django 3.1.12 on 2021-07-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_auto_20210706_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='shipping_address1',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='shipping_address2',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='shipping_address3',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='shipping_address4',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='shipping_address_city',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='shipping_address_country',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='shipping_address_postcode',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='shipping_address_state_county',
        ),
        migrations.RemoveField(
            model_name='quoteditem',
            name='currency',
        ),
        migrations.AlterField(
            model_name='quote',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Shipping Charges'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Discount %'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='sub_total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, null=True, verbose_name='Total'),
        ),
    ]
