# Generated by Django 3.1.12 on 2021-07-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_auto_20210706_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Shipping Charges'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='sub_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Sub Total'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Total'),
        ),
    ]
