# Generated by Django 3.1.12 on 2021-07-11 10:58

from django.db import migrations, models
import django.db.models.deletion
import quote.models


class Migration(migrations.Migration):

    dependencies = [
        ('vatRate', '0003_auto_20210701_2200'),
        ('quote', '0007_auto_20210706_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=11, verbose_name='Adjustment'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=quote.models.quote_attachment_directory_path, verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shipping_vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vatRate.vatrate'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.'), ('Ms.', 'Ms.'), ('', 'Prefer not to say')], default='', max_length=25, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='work_org_name',
            field=models.CharField(max_length=200, verbose_name='Work Organisation'),
        ),
        migrations.AlterField(
            model_name='quoteditem',
            name='vat_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vatRate.vatrate'),
        ),
    ]
