# Generated by Django 3.0.12 on 2021-02-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210227_0951'),
        ('feature', '0003_flag_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='subscription',
        ),
        migrations.AddField(
            model_name='flag',
            name='subscription',
            field=models.ManyToManyField(blank=True, help_text='Subscriptions for which this feature is active.', to='payment.Pricing', verbose_name='Subscriptions'),
        ),
    ]
