# Generated by Django 3.0.12 on 2021-02-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210227_0951'),
        ('feature', '0004_auto_20210227_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='subscription',
        ),
        migrations.AddField(
            model_name='flag',
            name='pricings',
            field=models.ManyToManyField(blank=True, help_text='Activate this flag for users with these subscriptions', to='payment.Pricing', verbose_name='Subscriptions'),
        ),
    ]
