# Generated by Django 3.0.12 on 2021-03-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='', help_text='Team Name', max_length=300, verbose_name='Team Name'),
        ),
    ]
