# Generated by Django 3.0.12 on 2021-03-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20210312_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
