# Generated by Django 3.0.12 on 2021-03-12 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_teammembership_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
