# Generated by Django 3.2.4 on 2021-06-20 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of the country')),
                ('official_name', models.CharField(max_length=300, verbose_name='Official Name of the country')),
                ('alphanumeric2_iso_code', models.CharField(max_length=2, verbose_name='Alpha-2 ISO Country code')),
                ('alphanumeric3_iso_code', models.CharField(max_length=3, verbose_name='Alpha-3 ISO Country code')),
                ('numeric_iso_code', models.IntegerField(verbose_name='Numeric-3 Currency code')),
                ('internet_root_zone_id', models.CharField(blank=True, max_length=2, verbose_name='Internet root zone id')),
                ('isActive', models.BooleanField(default=True)),
                ('dateTimeModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.currency')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Country',
            },
        ),
    ]
