# Generated by Django 3.2.4 on 2021-06-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='internet_root_zone_id',
            field=models.CharField(blank=True, max_length=8, verbose_name='Internet root zone id'),
        ),
        migrations.AlterField(
            model_name='country',
            name='numeric_iso_code',
            field=models.IntegerField(verbose_name='Numeric-3 country code'),
        ),
    ]
