# Generated by Django 3.2.4 on 2021-06-20 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0003_country_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_addedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
