# Generated by Django 3.2 on 2021-05-21 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0005_auto_20210309_1956'),
        ('teams', '0009_auto_20210317_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('dateTimeModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=200, verbose_name='Source')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss.', 'Miss.'), ('Ms.', 'Ms.'), ('', 'Prefer not to say')], default='', max_length=25, verbose_name='Title')),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='Age')),
                ('work_org_name', models.CharField(blank=True, max_length=200, verbose_name='Work organisation')),
                ('work_address1', models.CharField(blank=True, max_length=200, verbose_name='Address Line 1')),
                ('work_address2', models.CharField(blank=True, max_length=200, verbose_name='Address Line 2')),
                ('work_address3', models.CharField(blank=True, max_length=200, verbose_name='Address Line 3')),
                ('work_address4', models.CharField(blank=True, max_length=200, verbose_name='Address Line 4')),
                ('work_address_city', models.CharField(blank=True, max_length=60, verbose_name='City')),
                ('work_address_state_county', models.CharField(blank=True, max_length=60, verbose_name='State/County')),
                ('work_address_postcode', models.CharField(blank=True, max_length=60, verbose_name='State/County')),
                ('work_address_country', models.CharField(blank=True, max_length=60, verbose_name='Country')),
                ('work_Role', models.CharField(blank=True, max_length=200, verbose_name='Work Designation')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone number')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile number')),
                ('preferred_contact_preference', models.CharField(blank=True, choices=[('PHONE', 'Landline'), ('MOBILE.', 'Mobile'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('POST', 'Post')], max_length=20, verbose_name='Phone number')),
                ('preferred_contact_time', models.CharField(choices=[('Morning', 'Morning(before 9AM)'), ('MOBILE.', 'Work Hours(Between 9AM and 5PM)'), ('EVENING', 'Evening (Between 5PM to 8PM)')], default='MOBILE.', max_length=20, verbose_name='Preferred Contact Time')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('secondary_email', models.EmailField(blank=True, max_length=254, verbose_name='Secondary Email')),
                ('social_media_1', models.URLField(blank=True, verbose_name='Social Media Profile-1')),
                ('social_media_2', models.URLField(blank=True, verbose_name='Social Media Profile-2')),
                ('social_media_3', models.URLField(blank=True, verbose_name='Social Media Profile-3')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('lead_Ratings', models.CharField(blank=True, max_length=200, verbose_name='Lead Ratings')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Description')),
                ('closeReason', models.TextField(blank=True, max_length=200, verbose_name='Lead Close Reason')),
                ('external_ref1', models.CharField(blank=True, max_length=200, verbose_name='external reference number 1')),
                ('external_ref2', models.CharField(blank=True, max_length=200, verbose_name='external reference number 2')),
                ('external_ref3', models.CharField(blank=True, max_length=200, verbose_name='external reference number 3')),
                ('dateTimeModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinged_agent', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_Status', to='leads.category')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team')),
            ],
            options={
                'verbose_name': 'Leads',
                'verbose_name_plural': 'Leads',
            },
        ),
    ]
