# Generated by Django 3.2 on 2021-05-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='preferred_contact_preference',
            field=models.CharField(blank=True, choices=[('PHONE', 'Landline'), ('MOBILE.', 'Mobile'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('POST', 'Post')], default='EMAIL', max_length=20, verbose_name='Preferred Contact Method'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Leads/profile_pictures/'),
        ),
    ]
