# Generated by Django 3.2 on 2021-05-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
    ]
