# Generated by Django 3.2 on 2021-06-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20210603_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='nbr_of_employees',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of Employees'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='preferred_contact_time',
            field=models.CharField(choices=[('Morning', 'Morning(before 9AM)'), ('WorkHours', 'Work Hours(Between 9AM and 5PM)'), ('EVENING', 'Evening (Between 5PM to 8PM)')], default='WorkHours', max_length=20, verbose_name='Preferred Contact Time'),
        ),
    ]
