# Generated by Django 3.2 on 2021-06-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_lead_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notes',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
