# Generated by Django 3.2.4 on 2021-06-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20210612_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Lead Category', 'verbose_name_plural': 'Lead Category'},
        ),
    ]
