# Generated by Django 3.2.4 on 2021-06-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_category_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
