# Generated by Django 3.2.4 on 2021-06-20 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0001_initial"),
        ("country", "0003_country_language"),
        ("leads", "0017_lead_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="preferred_communication_language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="language.language",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="work_address_country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="country.country",
            ),
        ),
    ]
