# Generated by Django 3.2.4 on 2021-06-21 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
        ('leads', '0018_auto_20210620_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Industry', to='industry.industry'),
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
