# Generated by Django 3.2.4 on 2021-06-21 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('leads', '0019_auto_20210621_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_Status', to='category.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
