# Generated by Django 3.0.12 on 2021-02-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_org_name', models.CharField(blank=True, max_length=300, verbose_name='Work organisation')),
                ('work_Address', models.TextField(blank=True, verbose_name='Work Address')),
                ('is_verified', models.BooleanField(default=True)),
                ('is_access_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dateTimeModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('subscriptionType', models.TextField(blank=True, verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
    ]
