# Generated by Django 3.0.12 on 2021-02-27 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='subscriptionType',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='work_Address',
        ),
    ]
