# Generated by Django 3.0.12 on 2021-02-27 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20210227_0951'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='work_address_line1',
            field=models.CharField(default='', help_text='Required: First Line of address', max_length=60, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='work_address_line2',
            field=models.CharField(blank=True, max_length=60, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='work_address_line3',
            field=models.CharField(blank=True, max_length=60, verbose_name='Address Line 3'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='work_address_line4',
            field=models.CharField(blank=True, max_length=60, verbose_name='Address Line 4'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='work_address_postcode',
            field=models.CharField(default='', help_text='Required: Postcode', max_length=30, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='work_org_name',
            field=models.CharField(default='', help_text='Required: Organisation Name', max_length=300, verbose_name='Work organisation'),
        ),
    ]
