# Generated by Django 3.2.4 on 2021-06-20 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_organisation_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='country',
        ),
    ]
