# Generated by Django 3.2.4 on 2021-06-20 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20210620_2210'),
        ('organisation', '0008_auto_20210620_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='currency.currency'),
        ),
    ]
