# Generated by Django 3.2.4 on 2021-06-21 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
        ('organisation', '0009_organisation_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='industry.industry'),
        ),
    ]
