# Generated by Django 3.1.12 on 2021-07-11 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organisation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0010_organisation_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='bank_account_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Bank Account number'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='bank_account_sort_code',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sort Code'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='quote_template',
            field=models.FileField(blank=True, null=True, upload_to=organisation.models.quote_template_directory_path, verbose_name='Quote Template'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
