# Generated by Django 3.2.4 on 2021-06-20 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("prodUsageUnit", "0001_initial"),
        ("prodCategory", "0001_initial"),
        ("organisation", "0005_auto_20210309_1956"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prodManufacturer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=product.models.product_directory_path,
                    ),
                ),
                ("code", models.CharField(max_length=40, verbose_name="Product Code")),
                ("name", models.CharField(max_length=200, verbose_name="Product Name")),
                (
                    "isActive",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="Is Active"
                    ),
                ),
                (
                    "sale_start_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name="Sale start date",
                    ),
                ),
                (
                    "sale_end_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name="Sale end date",
                    ),
                ),
                (
                    "support_start_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name="Support start date",
                    ),
                ),
                (
                    "support_end_date",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        verbose_name="Support end date",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "comission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Unit Price",
                    ),
                ),
                (
                    "isTaxable",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Is Taxable"
                    ),
                ),
                (
                    "quantity_in_stock",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Current Stock"
                    ),
                ),
                (
                    "quantity_ordered",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Quantity Ordered"
                    ),
                ),
                (
                    "reorder_level",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Reorder level"
                    ),
                ),
                (
                    "quantity_in_demand",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Quantity in demand"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=400, verbose_name="Description"
                    ),
                ),
                (
                    "dateTimeModified",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified"),
                ),
                (
                    "dateTimeCreated",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prodCategory.prodcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_added_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_handler",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prodManufacturer.manufacturer",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organisation.organisation",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usage_unit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="prodUsageUnit.produsageunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
