# Generated by Django 3.2.4 on 2021-06-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="comission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Comission Rate",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tax",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Tax Rate"
            ),
        ),
    ]
