# Generated by Django 3.1.12 on 2021-07-01 20:10

from django.db import migrations, models
import product.validators


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210620_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=40, validators=[product.validators.validate_code], verbose_name='Product Code'),
        ),
    ]
