# Generated by Django 3.2.4 on 2021-06-20 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphanumeric_iso_code', models.CharField(max_length=3, verbose_name='Alpha ISO Currency code')),
                ('numeric_iso_code', models.IntegerField(verbose_name='Numeric ISO Currency code')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('symbol', models.CharField(blank=True, max_length=1, verbose_name='Product Usage Unit')),
                ('decimal_sepeartor', models.IntegerField(default=2, verbose_name='Decimal Seperator')),
                ('thousand_seperator', models.CharField(blank=True, max_length=1, verbose_name='Product Usage Unit')),
                ('isActive', models.BooleanField(default=True)),
                ('dateTimeModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currency',
            },
        ),
    ]
