# Generated by Django 3.0.12 on 2021-04-05 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0009_auto_20210325_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='name',
            field=models.CharField(choices=[('FreeTrial', 'Free Trial'), ('FreeForLife', 'Free For Life'), ('Basic', 'Basic'), ('Essential', 'Essential'), ('Enterprise', 'Enterprise'), ('Individual', 'Individual'), ('Team', 'Team'), ('Organisation', 'Organisation')], default='FreeTrial', max_length=100, verbose_name='Pricing Type'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=50, verbose_name='Stripe subscription Id')),
                ('type', models.CharField(blank=True, max_length=60, verbose_name='Type of card')),
                ('brand', models.CharField(blank=True, max_length=60, verbose_name='Card Brand')),
                ('country', models.CharField(blank=True, max_length=60, verbose_name='Card country')),
                ('expiry_month', models.CharField(blank=True, max_length=2, verbose_name='Card Expiry Month')),
                ('expiry_year', models.CharField(blank=True, max_length=4, verbose_name='Card Expiry Month')),
                ('last4', models.CharField(blank=True, max_length=4, verbose_name='Last 4 Digits')),
                ('is_default', models.BooleanField(default=True)),
                ('dateTimeModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
