# Generated by Django 3.1.12 on 2021-07-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_paymentmethod_expiry_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_month',
            field=models.CharField(blank=True, choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=2, verbose_name='Card Expiry Month'),
        ),
    ]
