# Generated by Django 3.2.4 on 2021-06-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodManufacturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
