# Generated by Django 3.1.12 on 2021-07-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vatRate', '0002_auto_20210701_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='VAT Rate %'),
        ),
    ]
