# Generated by Django 3.2 on 2021-05-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210530_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Leads/profile_pictures/'),
        ),
    ]
