# Generated by Django 3.2 on 2021-06-03 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0008_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='annual_revenue',
            field=models.IntegerField(blank=True, default=0, verbose_name='Annual Revenue'),
        ),
        migrations.AddField(
            model_name='lead',
            name='emailOptIn',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Email Opt In'),
        ),
        migrations.AddField(
            model_name='lead',
            name='emailOptInStatusChangeDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Email Opt In Date Time maintained'),
        ),
        migrations.AddField(
            model_name='lead',
            name='nbr_of_employees',
            field=models.IntegerField(blank=True, default=0, verbose_name='Annual Revenue'),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('dateTimeModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('dateTimeCreated', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industry',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Industry', to='leads.industry'),
        ),
    ]
