# Generated by Django 3.2 on 2021-06-05 00:20

from django.db import migrations, models
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20210604_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=leads.models.lead_profile_image_directory_path),
        ),
    ]
