# Generated by Django 3.2 on 2021-06-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_note_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(max_length=200, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='preferred_contact_time',
            field=models.CharField(choices=[('MORNING', 'Morning(before 9AM)'), ('WORKHOURS', 'Work Hours(Between 9AM and 5PM)'), ('EVENING', 'Evening (Between 5PM to 8PM)')], default='WORKHOURS', max_length=20, verbose_name='Preferred Contact Time'),
        ),
    ]
