# Generated by Django 3.0.12 on 2021-03-12 21:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0005_teammembership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('team', 'member')},
        ),
    ]
