# Generated by Django 3.0.12 on 2021-02-27 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210227_0951'),
        ('feature', '0002_flag_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='subscription',
            field=models.ForeignKey(blank=True, default=1, help_text='Subscriptions for which this feature is active.', on_delete=django.db.models.deletion.CASCADE, to='payment.Pricing', verbose_name='Subscriptions'),
            preserve_default=False,
        ),
    ]
