# Generated by Django 3.2.4 on 2021-06-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0002_industry_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='sector',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sector'),
        ),
    ]
